import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../../../../packages/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  adjustFontFallback: false,
  fallback: ["sans", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className={`${pretendard.className} flex min-h-full flex-col`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
